export const EVENTS = {
  USER_CREATED: "USER_CREATED",
  COMPANY_CREATED: "COMPANY_CREATED",
  DIAGNOSTIC_STARTED: "DIAGNOSTIC_STARTED",
  DIAGNOSTIC_COMPLETED: "DIAGNOSTIC_COMPLETED",
  AUTOMATION_OPPORTUNITY_DETECTED: "AUTOMATION_OPPORTUNITY_DETECTED",
  AUTOMATION_VIEWED: "AUTOMATION_VIEWED",
  AUTOMATION_SIMULATED: "AUTOMATION_SIMULATED",
  AUTOMATION_ACCEPTED: "AUTOMATION_ACCEPTED",
  AUTOMATION_REJECTED: "AUTOMATION_REJECTED",
  AUTOMATION_PURCHASED: "AUTOMATION_PURCHASED",
  AUTOMATION_INSTALLED: "AUTOMATION_INSTALLED",
  AUTOMATION_DEACTIVATED: "AUTOMATION_DEACTIVATED",
  AUTOMATION_REACTIVATED: "AUTOMATION_REACTIVATED",
  SUBSCRIPTION_STARTED: "SUBSCRIPTION_STARTED",
  SUBSCRIPTION_CANCELLED: "SUBSCRIPTION_CANCELLED",
  FEEDBACK_SUBMITTED: "FEEDBACK_SUBMITTED",
  RECOMMENDATION_SHOWN: "RECOMMENDATION_SHOWN",
  AUTOMATION_EXECUTED: "AUTOMATION_EXECUTED",
  AUTOMATION_EXECUTION_ISSUE: "AUTOMATION_EXECUTION_ISSUE",
} as const;

export type EventType = (typeof EVENTS)[keyof typeof EVENTS];
