import Link from "next/link";
import { SiteHeader } from "@/components/marketing/SiteHeader";

const sections = [
  ["1. Éditeur et champ d'application", "Pilotzia est édité par EVOLUSS, SASU, dont le siège social est situé 1 rue Marguerin, 75014 Paris, France. Les présentes conditions générales de vente s'appliquent aux clients professionnels (B2B) utilisant Pilotzia en France métropolitaine et dans les territoires français d'outre-mer, sauf conditions particulières convenues par écrit."],
  ["2. Service", "Pilotzia fournit un copilote opérationnel permettant notamment de structurer le contexte métier d'une entreprise, d'analyser des informations, de recommander des actions, de piloter certaines automatisations, de maintenir un Business Graph et de suivre les résultats déclarés ou observés. Les fonctionnalités disponibles dépendent de l'offre souscrite, du niveau d'autorisation choisi et des intégrations réellement configurées."],
  ["3. Essai", "Une première analyse gratuite peut être proposée. L'essai applicatif démarre au premier usage IA réel et reste soumis à une durée, un nombre de crédits et un plafond de coût. L'essai peut prendre fin dès qu'un de ces plafonds est atteint. La fin de l'essai ne supprime pas automatiquement le contexte ou l'historique déjà enregistré."],
  ["4. Prix", "Sauf indication contraire au moment de la souscription, les offres publiques de référence sont Core à 79 € HT par mois (869 € HT par an), Action à 179 € HT par mois (1 969 € HT par an) et Scale à 399 € HT par mois (4 389 € HT par an). Action et Scale donnent accès au moteur d'exécution. Les automatisations exécutables sont des achats uniques distincts de l'abonnement, aux prix HT affichés avant validation. Leur utilisation ultérieure peut consommer les crédits compris dans l'offre ou achetés en complément. Les sièges additionnels ou autres prestations éventuelles font l'objet d'un prix ou d'un devis présenté avant engagement."],
  ["5. Facturation et paiement", "Les abonnements, crédits et achats d'automatisations sont facturés par l'intermédiaire de Stripe ou du prestataire de paiement indiqué lors de la commande. Lorsqu'un moyen de paiement est déjà associé au compte de l'entreprise, le Propriétaire peut autoriser un achat d'automatisation sans ressaisir systématiquement les données de carte. Le prestataire de paiement ou la banque peut toutefois imposer une authentification ou confirmation supplémentaire. Aucun workflow acheté n'est installé avant confirmation du paiement. Pilotzia applique en outre des plafonds de crédits, de coût variable et, lorsque cette fonction est activée, un plafond mensuel d'achats d'automatisations."],
  ["6. Abonnement sans engagement", "Les offres mensuelles sont sans engagement de durée au-delà de la période déjà payée. Le client peut demander la résiliation à tout moment ; elle prend effet à la fin de la période de facturation en cours, sauf disposition contraire affichée lors de la commande. Une formule annuelle reste due pour la période annuelle souscrite sauf droit ou accord contraire."],
  ["7. Renouvellement et résiliation", "Sauf résiliation préalable, l'abonnement se renouvelle automatiquement pour une période équivalente à celle choisie. La résiliation peut être demandée depuis l'espace de facturation ou selon la procédure indiquée dans Pilotzia. Sauf obligation légale, erreur de facturation ou geste commercial express, une période déjà commencée n'est pas remboursée au prorata."],
  ["8. Crédits, automatisations et capacité", "Chaque offre comprend une capacité mensuelle d'usage intelligent. Les crédits couvrent notamment les analyses et l'usage opérationnel des fonctionnalités ou automatisations, mais ne constituent pas le prix d'achat initial d'une automatisation. Une automatisation achetée reste associée à l'entreprise conformément aux conditions du service ; son exécution nécessite néanmoins une offre et une capacité d'usage compatibles. Pilotzia peut proposer des packs de crédits ou des sièges supplémentaires. Les consommations et achats sont soumis à des garde-fous de coût, à des règles d'idempotence et aux permissions de l'entreprise."],
  ["9. Obligations du client", "Le client s'engage à fournir des informations exactes, à utiliser le service conformément à la loi, à ne connecter ou importer que les systèmes et données pour lesquels il dispose des droits nécessaires, à gérer correctement les habilitations de son équipe et à protéger ses accès."],
  ["10. Permissions et actions", "Pilotzia distingue la lecture, la préparation d'action, l'action avec confirmation et l'autonomie encadrée. Le client reste responsable du niveau d'autorisation accordé et des validations confirmées. Une modification d'une configuration sensible, par exemple le message, la cadence, le périmètre ou les horaires d'une automatisation, peut invalider l'autorisation précédente et exiger une nouvelle validation."],
  ["11. Achat, activation et usage des automatisations", "Le prix d'achat unique d'une automatisation est présenté avant validation. Seul un rôle disposant de la permission de facturation peut engager cet achat. Un plafond mensuel d'achat peut être configuré afin de bloquer techniquement toute nouvelle dépense au-delà du montant autorisé ; ce plafond ne déclenche jamais d'achat automatique. Après paiement, l'installation et l'activation restent soumises aux permissions et validations applicables. Lorsqu'une automatisation envoie une communication, Pilotzia peut conserver la preuve de l'exécution, notamment le destinataire, le message rendu, l'horodatage, la version, le fournisseur et l'identifiant fournisseur lorsqu'il est disponible. Le client demeure responsable de la légalité de ses communications et de la gestion des exclusions ou oppositions applicables."],
  ["12. Services tiers", "Certaines fonctions dépendent de services externes, notamment des fournisseurs d'IA, d'hébergement, de paiement, d'email, d'orchestration ou des applications connectées. Une interruption, une modification de prix, de politique ou d'API chez un tiers peut affecter temporairement une fonction de Pilotzia."],
  ["13. Données et confidentialité", "Le traitement des données personnelles est décrit dans la politique de confidentialité. EVOLUSS ne commercialise pas les données brutes des clients. Les systèmes sources restent l'autorité de référence pour les données qui y résident."],
  ["14. Estimations, recommandations et résultats", "Les scores, opportunités, gains de temps potentiels, estimations de valeur et recommandations constituent des aides à la décision et ne garantissent aucun résultat financier ou commercial. Pilotzia distingue ces estimations des résultats effectivement observés ou déclarés par un utilisateur. Un résultat déclaré par un utilisateur est présenté comme tel et n'est pas assimilé à une mesure indépendante du fournisseur."],
  ["15. Rafraîchissement et apprentissage", "Pilotzia peut rafraîchir automatiquement le contexte et les sources autorisées, notamment sur une base hebdomadaire. Ce rafraîchissement respecte les permissions du client et peut être limité pour maîtriser les coûts et éviter des traitements inutiles. Une absence de changement significatif peut conduire à ne déclencher aucune analyse IA payante."],
  ["16. Disponibilité", "EVOLUSS met en œuvre des moyens raisonnables pour maintenir Pilotzia disponible et fiable, sans garantir une disponibilité ininterrompue. Des maintenances, incidents, limites de prestataires, migrations d'infrastructure ou mesures de sécurité peuvent entraîner des interruptions temporaires."],
  ["17. Responsabilité", "Dans les limites permises par la loi et sauf faute lourde, dol ou obligation impérative contraire, la responsabilité d'EVOLUSS est limitée aux dommages directs et prévisibles résultant d'un manquement prouvé. Le client reste responsable de ses décisions métiers, de la légalité des données qu'il traite et des actions qu'il autorise."],
  ["18. Propriété intellectuelle", "Le logiciel, la marque Pilotzia, les interfaces, modèles, catalogues, méthodes et éléments fournis par EVOLUSS restent protégés par les droits de propriété intellectuelle applicables. Le client conserve ses droits sur ses données et contenus."],
  ["19. Évolution du service et des conditions", "Pilotzia peut évoluer pour améliorer sa sécurité, ses performances, ses intégrations ou ses fonctionnalités. Les changements contractuels substantiels applicables à un abonnement en cours sont communiqués dans un délai raisonnable lorsque cela est requis."],
  ["20. Droit applicable", "Les présentes conditions sont régies par le droit français. En cas de différend, les parties s'efforcent de rechercher une solution amiable avant toute action. À défaut d'accord, la compétence juridictionnelle est déterminée conformément aux règles applicables au litige et à la qualité des parties."],
  ["21. Contact", "Pour toute question contractuelle, de facturation ou relative au service : contact@pilotzia.com. Pour les demandes relatives aux données personnelles : dpo-contact@pilotzia.com."],
];

export default function CgvPage() {
  return (
    <div className="min-h-screen bg-background">
      <SiteHeader />
      <main className="mx-auto max-w-4xl px-6 py-12 sm:py-16">
        <p className="text-xs font-semibold uppercase tracking-[0.18em] text-accent">Contrat B2B</p>
        <h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Conditions générales de vente</h1>
        <p className="mt-4 text-sm leading-6 text-muted-foreground">Dernière mise à jour : 18 septembre 2026.</p>
        <div className="mt-10 space-y-7">
          {sections.map(([title, body]) => (
            <section key={title}>
              <h2 className="font-semibold">{title}</h2>
              <p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p>
            </section>
          ))}
        </div>
        <p className="mt-10 text-sm text-muted-foreground">
          La <Link href="/confidentialite" className="font-semibold text-accent">politique de confidentialité</Link> est distincte des présentes CGV.
        </p>
      </main>
    </div>
  );
}
