import { AutomationTemplate } from "./types";

// Catalogue vivant d'automatisations — pas des milliers de workflows inutiles,
// un socle réaliste qui couvre les besoins les plus fréquents des PME.
// Cycle prévu à terme : Demand → Generate → Test → Validate → Publish → Measure → Improve.
export const AUTOMATION_CATALOG: AutomationTemplate[] = [
  {
    id: "relance-prospects",
    title: "Relance automatique des prospects",
    businessGoal: "Ne plus jamais oublier de relancer un prospect silencieux",
    description:
      "Détecte les prospects sans réponse depuis plusieurs jours et déclenche une relance personnalisée au bon moment.",
    category: "Ventes",
    keywords: ["relance", "prospect", "suivre", "followup", "relancer", "ne répond pas", "silence"],
    relevantTools: ["Gmail", "Outlook", "HubSpot", "Pipedrive", "Salesforce"],
    impactLevel: "high",
    complexity: "low",
    estimatedHoursPerMonth: 8,
    priceEur: 29,
    steps: [
      "Détecter un prospect sans réponse depuis X jours",
      "Vérifier son statut dans le CRM",
      "Envoyer une relance personnalisée",
      "Informer le commercial concerné",
    ],
  },
  {
    id: "qualification-leads",
    title: "Qualification des nouveaux leads",
    businessGoal: "Ne traiter en priorité que les prospects les plus prometteurs",
    description:
      "Analyse chaque nouveau contact entrant, l'enrichit et l'attribue automatiquement au bon commercial.",
    category: "Ventes",
    keywords: ["lead", "qualifier", "formulaire", "nouveau contact", "qualification"],
    relevantTools: ["HubSpot", "Salesforce", "Pipedrive"],
    impactLevel: "high",
    complexity: "medium",
    estimatedHoursPerMonth: 5,
    priceEur: 49,
    steps: [
      "Détecter un nouveau lead entrant",
      "Enrichir les informations disponibles",
      "Attribuer un score de qualification",
      "Router vers le bon commercial",
    ],
  },
  {
    id: "notification-leads",
    title: "Notification des nouveaux leads",
    businessGoal: "Réagir en quelques minutes à chaque opportunité entrante",
    description: "Alerte immédiatement l'équipe commerciale dès qu'un nouveau lead entre dans le CRM.",
    category: "Ventes",
    keywords: ["notifier", "alerte", "nouveau lead", "slack", "équipe", "prévenir"],
    relevantTools: ["HubSpot", "Salesforce", "Pipedrive", "Slack", "Microsoft Teams"],
    impactLevel: "medium",
    complexity: "low",
    estimatedHoursPerMonth: 2,
    priceEur: 19,
    steps: [
      "Détecter un nouveau lead dans le CRM",
      "Formater les informations clés",
      "Publier une alerte dans le canal d'équipe",
    ],
  },
  {
    id: "compte-rendu-reunion",
    title: "Génération des comptes-rendus de réunion",
    businessGoal: "Ne plus jamais retranscrire une réunion à la main",
    description: "Transforme automatiquement chaque réunion en compte-rendu structuré avec les actions à suivre.",
    category: "Productivité",
    keywords: ["compte-rendu", "réunion", "notes", "résumé", "meeting", "retranscrire"],
    relevantTools: ["Zoom", "Google Meet", "Notion", "Microsoft Teams"],
    impactLevel: "medium",
    complexity: "medium",
    estimatedHoursPerMonth: 3,
    priceEur: 39,
    steps: [
      "Récupérer la transcription de la réunion",
      "Générer un résumé structuré",
      "Extraire les actions à suivre",
      "Publier le compte-rendu dans l'espace partagé",
    ],
  },
  {
    id: "sync-crm-facturation",
    title: "Synchronisation CRM et facturation",
    businessGoal: "Avoir une vision fiable et à jour de chaque client payant",
    description: "Garde le CRM et les outils de facturation parfaitement synchronisés sans ressaisie manuelle.",
    category: "Opérations",
    keywords: ["synchroniser", "facture", "stripe", "client", "crm", "facturation"],
    relevantTools: ["Stripe", "HubSpot", "Salesforce", "Pipedrive"],
    impactLevel: "medium",
    complexity: "medium",
    estimatedHoursPerMonth: 4,
    priceEur: 59,
    steps: [
      "Détecter un nouveau client payant",
      "Créer ou mettre à jour la fiche CRM",
      "Synchroniser le statut de facturation",
    ],
  },
  {
    id: "relance-factures",
    title: "Relances de factures impayées",
    businessGoal: "Être payé à temps sans avoir à relancer soi-même",
    description: "Surveille les échéances de paiement et relance automatiquement les factures impayées.",
    category: "Finance",
    keywords: ["facture", "impayé", "relance", "paiement", "comptabilité", "règlement"],
    relevantTools: ["Stripe", "Gmail", "Outlook"],
    impactLevel: "high",
    complexity: "low",
    estimatedHoursPerMonth: 4,
    priceEur: 29,
    steps: [
      "Détecter une facture arrivée à échéance",
      "Vérifier si le paiement a été reçu",
      "Envoyer une relance automatique",
      "Escalader après plusieurs relances",
    ],
  },
  {
    id: "onboarding-clients",
    title: "Onboarding automatique des nouveaux clients",
    businessGoal: "Offrir un accueil impeccable à chaque nouveau client, sans effort manuel",
    description: "Déclenche automatiquement la séquence de bienvenue et prépare l'espace de travail du client.",
    category: "Opérations",
    keywords: ["onboarding", "nouveau client", "bienvenue", "accès", "accueil"],
    relevantTools: ["Notion", "HubSpot", "Gmail", "Outlook"],
    impactLevel: "high",
    complexity: "medium",
    estimatedHoursPerMonth: 6,
    priceEur: 79,
    steps: [
      "Détecter un nouveau client actif",
      "Envoyer la séquence de bienvenue",
      "Créer l'espace de travail dédié",
      "Informer l'équipe concernée",
    ],
  },
  {
    id: "support-questions-frequentes",
    title: "Réponses automatiques aux questions fréquentes",
    businessGoal: "Répondre plus vite à son support client sans y passer ses journées",
    description: "Identifie les demandes récurrentes et propose une réponse adaptée avant escalade humaine.",
    category: "Support",
    keywords: ["support", "question", "ticket", "client", "réponse", "service client"],
    relevantTools: ["Gmail", "Outlook", "Slack"],
    impactLevel: "medium",
    complexity: "medium",
    estimatedHoursPerMonth: 7,
    priceEur: 59,
    steps: [
      "Détecter un nouveau ticket entrant",
      "Identifier la nature de la demande",
      "Proposer une réponse adaptée",
      "Escalader vers un humain si nécessaire",
    ],
  },
  {
    id: "publication-reseaux-sociaux",
    title: "Publication automatique sur les réseaux sociaux",
    businessGoal: "Garder une présence régulière sans y penser chaque jour",
    description: "Publie le contenu planifié au bon format et au bon moment sur chaque réseau.",
    category: "Marketing",
    keywords: ["réseaux sociaux", "publication", "contenu", "social media", "instagram", "linkedin"],
    relevantTools: ["Notion", "Google Sheets", "Airtable"],
    impactLevel: "medium",
    complexity: "low",
    estimatedHoursPerMonth: 3,
    priceEur: 29,
    steps: [
      "Récupérer le contenu planifié",
      "Adapter le format à chaque réseau",
      "Publier automatiquement à l'heure prévue",
    ],
  },
  {
    id: "suivi-satisfaction",
    title: "Suivi automatique de la satisfaction client",
    businessGoal: "Détecter un client mécontent avant qu'il ne parte",
    description: "Envoie une enquête courte après chaque prestation et alerte en cas d'insatisfaction.",
    category: "Support",
    keywords: ["satisfaction", "feedback", "avis", "nps", "client"],
    relevantTools: ["Gmail", "Outlook", "HubSpot"],
    impactLevel: "medium",
    complexity: "low",
    estimatedHoursPerMonth: 2,
    priceEur: 19,
    steps: [
      "Détecter la clôture d'une prestation",
      "Envoyer une enquête de satisfaction courte",
      "Centraliser les réponses",
      "Alerter en cas d'insatisfaction",
    ],
  },
  {
    id: "generation-devis",
    title: "Génération automatique de devis",
    businessGoal: "Envoyer un devis en quelques minutes au lieu de plusieurs heures",
    description: "Génère et envoie automatiquement un devis dès qu'une demande qualifiée est détectée.",
    category: "Ventes",
    keywords: ["devis", "proposition commerciale", "tarif", "offre"],
    relevantTools: ["HubSpot", "Salesforce", "Pipedrive", "Notion"],
    impactLevel: "high",
    complexity: "medium",
    estimatedHoursPerMonth: 5,
    priceEur: 59,
    steps: [
      "Détecter une demande de devis qualifiée",
      "Générer le document à partir du modèle",
      "Envoyer au prospect pour validation",
      "Relancer en l'absence de réponse",
    ],
  },
  {
    id: "reporting-hebdo",
    title: "Reporting hebdomadaire automatique",
    businessGoal: "Garder toute l'équipe alignée sans réunion de suivi supplémentaire",
    description: "Compile automatiquement les indicateurs clés de la semaine et les diffuse à l'équipe.",
    category: "Productivité",
    keywords: ["rapport", "reporting", "suivi", "kpi", "tableau de bord"],
    relevantTools: ["Google Sheets", "Excel", "Slack", "Microsoft Teams", "Google Analytics 4", "Google Ads", "Meta Ads", "LinkedIn Ads"],
    impactLevel: "medium",
    complexity: "low",
    estimatedHoursPerMonth: 3,
    priceEur: 29,
    steps: [
      "Collecter les données clés de la semaine",
      "Générer un résumé lisible",
      "Diffuser automatiquement à l'équipe",
    ],
  },
  {
    id: "gestion-candidatures",
    title: "Gestion automatique des candidatures",
    businessGoal: "Ne plus laisser un bon candidat sans réponse",
    description: "Trie chaque candidature reçue, notifie le recruteur concerné et envoie un accusé de réception.",
    category: "RH",
    keywords: ["recrutement", "candidature", "cv", "rh", "candidat"],
    relevantTools: ["Gmail", "Outlook", "Google Sheets", "Airtable"],
    impactLevel: "medium",
    complexity: "medium",
    estimatedHoursPerMonth: 4,
    priceEur: 49,
    steps: [
      "Détecter une nouvelle candidature",
      "Trier selon les critères définis",
      "Notifier le recruteur concerné",
      "Envoyer un accusé de réception",
    ],
  },
  {
    id: "sync-stock-ecommerce",
    title: "Synchronisation des stocks e-commerce",
    businessGoal: "Ne plus jamais vendre un produit en rupture de stock",
    description: "Maintient l'inventaire à jour en temps réel et alerte en cas de rupture imminente.",
    category: "Opérations",
    keywords: ["stock", "ecommerce", "shopify", "inventaire", "produit", "rupture"],
    relevantTools: ["Shopify", "Google Sheets", "Excel"],
    impactLevel: "high",
    complexity: "medium",
    estimatedHoursPerMonth: 6,
    priceEur: 79,
    steps: [
      "Détecter une variation de stock",
      "Mettre à jour l'inventaire central",
      "Alerter en cas de rupture",
    ],
  },
  {
    id: "veille-concurrence",
    title: "Veille automatique de la concurrence",
    businessGoal: "Rester informé du marché sans y passer une heure par semaine",
    description: "Surveille les sources définies et diffuse un résumé des informations pertinentes à l'équipe.",
    category: "Marketing",
    keywords: ["veille", "concurrence", "marché", "actualité"],
    relevantTools: ["Notion", "Slack", "Microsoft Teams"],
    impactLevel: "low",
    complexity: "low",
    estimatedHoursPerMonth: 2,
    priceEur: 19,
    steps: [
      "Surveiller les sources définies",
      "Filtrer les informations pertinentes",
      "Résumer et diffuser à l'équipe",
    ],
  },
];

export function getTemplateById(id: string): AutomationTemplate | undefined {
  return AUTOMATION_CATALOG.find((t) => t.id === id);
}
